export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOAD_BOOKS_REQUEST = 'LOAD_BOOKS_REQUEST';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'LOAD_BOOKS_FAILURE';

export const LOAD_BOOK_REQUEST = 'LOAD_BOOK_REQUEST';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';
export const LOAD_BOOK_FAILURE = 'LOAD_BOOK_FAILURE';

export const LOAD_FAVORITE_BOOKS_REQUEST = 'LOAD_FAVORITE_BOOKS_REQUEST';
export const LOAD_FAVORITE_BOOKS_SUCCESS = 'LOAD_FAVORITE_BOOKS_SUCCESS';

export const SET_YEAR = 'SET_YEAR';
export const SET_RATING = 'SET_RATING';
export const SET_GENRE = 'SET_GENRE';
export const SET_SORTING = 'SET_SORTING';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
